import React from 'react';
import { Terminal, Shield, RefreshCcw, Activity } from 'lucide-react';
import { SimulationLog } from '../../types/architecture';

interface ArchitectureTelemetryProps {
  logs: SimulationLog[];
  onClear: () => void;
}

/**
 * Terminal-styled console viewport displaying live logs and telemetry packets
 * generated by active system components or sandbox simulation script runs.
 *
 * @component
 * @purpose
 * Provides immediate feedback on system-wide operations, capturing details about model execution,
 * cryptographic handshakes, and energy optimization schedules.
 *
 * @responsibilities
 * - Displays diagnostic logs in reverse-chronological order.
 * - Colors message envelopes based on severity levels (info, warning, success, error).
 * - Implements a clear buffer reset trigger back to the state hook.
 *
 * @param {ArchitectureTelemetryProps} props - Component properties.
 * @returns {React.ReactElement} The scrolling diagnostic log console.
 */
export const ArchitectureTelemetry: React.FC<ArchitectureTelemetryProps> = ({ logs, onClear }) => {
  return (
    <div className="bg-slate-950/80 border border-slate-800 rounded-2xl p-5 shadow-2xl backdrop-blur-md flex flex-col h-[220px]">
      
      {/* HUD Header */}
      <div className="flex items-center justify-between border-b border-slate-800 pb-3 mb-3">
        <div className="flex items-center space-x-2">
          <Terminal size={16} className="text-blue-400" />
          <span className="text-xs font-bold text-slate-300 uppercase tracking-widest font-mono">
            Nexus Protocol Telemetry Stream
          </span>
          <span className="relative flex h-2 w-2">
            <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-green-400 opacity-75"></span>
            <span className="relative inline-flex rounded-full h-2 w-2 bg-green-500"></span>
          </span>
        </div>

        <div className="flex items-center space-x-3 text-[10px] font-mono">
          <span className="text-slate-500 hidden sm:inline">BUFFER: {logs.length}/50 PACKETS</span>
          <button
            onClick={onClear}
            className="text-slate-400 hover:text-white flex items-center space-x-1 hover:underline transition-all"
            title="Clear Stream logs"
          >
            <RefreshCcw size={10} />
            <span>RESET STREAM</span>
          </button>
        </div>
      </div>

      {/* Terminal logs list */}
      <div className="flex-1 overflow-y-auto font-mono text-xs space-y-2 pr-1 custom-scrollbar">
        {logs.length === 0 ? (
          <div className="text-slate-600 italic h-full flex items-center justify-center">
            No telemetry data inside the stream. Trigger system commands to populate logs.
          </div>
        ) : (
          logs.map((log) => {
            const levelColors = {
              info: 'text-slate-300 border-slate-850',
              warning: 'text-yellow-400 border-yellow-950 bg-yellow-950/10',
              success: 'text-green-400 border-green-950 bg-green-950/10',
              error: 'text-red-400 border-red-950 bg-red-950/10'
            };

            return (
              <div 
                key={log.id} 
                className={`flex items-start py-1 px-2.5 rounded border ${levelColors[log.level]} transition-all duration-300 animate-fade-in`}
              >
                {/* Time stamp */}
                <span className="text-[10px] text-slate-500 mr-2 select-none">
                  [{log.timestamp}]
                </span>

                {/* Sender Module label */}
                <span className="text-[10px] text-blue-400/80 font-bold uppercase mr-2.5 min-w-[120px] select-none truncate">
                  {log.module}:
                </span>

                {/* Log content */}
                <span className="flex-1 font-medium select-text break-all">
                  {log.message}
                </span>
              </div>
            );
          })
        )}
      </div>
    </div>
  );
};
export default ArchitectureTelemetry;
